#
# Rclone config, set up to mount onedrive automatically
#

{ pkgs, ... }:
{
  home.packages = with pkgs; [
    kdePackages.dolphin
  ];

  # Config file copied from the one generated by dolphin after setting desired settings
  xdg.configFile."dolphinrc".text = ''
[General]
RememberOpenedTabs=false
Version=202
ViewPropsTimestamp=2025,4,15,11,24,43.846

[KFileDialog Settings]
Places Icons Auto-resize=false
Places Icons Static Size=22

[MainWindow]
MenuBar=Disabled

[PreviewSettings]
Plugins=appimagethumbnail,audiothumbnail,blenderthumbnail,comicbookthumbnail,cursorthumbnail,djvuthumbnail,ebookthumbnail,exrthumbnail,directorythumbnail,fontthumbnail,imagethumbnail,jpegthumbnail,kraorathumbnail,windowsexethumbnail,windowsimagethumbnail,mobithumbnail,opendocumentthumbnail,gsthumbnail,rawthumbnail,svgthumbnail,ffmpegthumbs
'';
}
